# Generated by Django 3.0.4 on 2020-04-06 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('creation_datetime', 'price')},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reduced_price',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Buy', 'Buy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Saloon', 'Saloon'), ('Cabriolet / Roadster', 'Cabriolet / Roadster'), ('Estate Car', 'Estate Car'), ('Small Car', 'Small Car'), ('Sports Car / Coupe', 'Sports Car / Coupe'), ('SUV / Off-road Vehicle', 'SUV / Off-road Vehicle'), ('Van / Minibus', 'Van / Minibus'), ('Pickup Truck', 'Pickup Truck'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, choices=[('Abarth', 'Abarth'), ('AC', 'AC'), ('Acura', 'Acura'), ('Aixam', 'Aixam'), ('Alfa Romeo', 'Alfa Romeo'), ('ALPINA', 'ALPINA'), ('Artega', 'Artega'), ('Asia Motors', 'Asia Motors'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Austin', 'Austin'), ('Austin Healey', 'Austin Healey'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Borgward', 'Borgward'), ('Brilliance', 'Brilliance'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Casalini', 'Casalini'), ('Caterham', 'Caterham'), ('Chatenet', 'Chatenet'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroën'), ('Cobra', 'Cobra'), ('Corvette', 'Corvette'), ('Cupra', 'Cupra'), ('Dacia', 'Dacia'), ('Daewoo', 'Daewoo'), ('Daihatsu', 'Daihatsu'), ('DeTomaso', 'DeTomaso'), ('Dodge', 'Dodge'), ('Donkervoort', 'Donkervoort'), ('DS Automobiles', 'DS Automobiles'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Fisker', 'Fisker'), ('Ford', 'Ford'), ('GM', 'GM'), ('GAC Gonow', 'GAC Gonow'), ('Gemballa', 'Gemballa'), ('GMC', 'GMC'), ('Grecav', 'Grecav'), ('Hamann', 'Hamann'), ('Holden', 'Holden'), ('Honda', 'Honda'), ('Hummer', 'Hummer'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Isuzu', 'Isuzu'), ('Iveco', 'Iveco'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Koenigsegg', 'Koenigsegg'), ('KTM', 'KTM'), ('Lada', 'Lada'), ('Lamborghini', 'Lamborghini'), ('Lancia', 'Lancia'), ('Land Rover', 'Land Rover'), ('Landwind', 'Landwind'), ('Lexus', 'Lexus'), ('Ligier', 'Ligier'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Mahindra', 'Mahindra'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('MG', 'MG'), ('Microcar', 'Microcar'), ('MINI', 'MINI'), ('Mitsubishi', 'Mitsubishi'), ('Morgan', 'Morgan'), ('Nissan', 'Nissan'), ('NSU', 'NSU'), ('Oldsmobile', 'Oldsmobile'), ('Opel', 'Opel'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Piaggio', 'Piaggio'), ('Plymouth', 'Plymouth'), ('Polestar', 'Polestar'), ('Pontiac', 'Pontiac'), ('Porsche', 'Porsche'), ('Proton', 'Proton'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Rover', 'Rover'), ('Ruf', 'Ruf'), ('Saab', 'Saab'), ('Santana', 'Santana'), ('Seat', 'Seat'), ('Skoda', 'Skoda'), ('Smart', 'Smart'), ('speedART', 'speedART'), ('Spyker', 'Spyker'), ('Ssangyong', 'Ssangyong'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Talbot', 'Talbot'), ('Tata', 'Tata'), ('TECHART', 'TECHART'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Trabant', 'Trabant'), ('Triumph', 'Triumph'), ('TVR', 'TVR'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Wartburg', 'Wartburg'), ('Westfield', 'Westfield'), ('Wiesmann', 'Wiesmann'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_of_import',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='displacement_cm',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pictures',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power_kw',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model_other',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
