# Generated by Django 3.0.4 on 2020-03-28 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0002_auto_20200326_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Saloon', 'Saloon'), ('Cabriolet / Roadster', 'Cabriolet / Roadster'), ('Estate Car', 'Estate Car'), ('Small Car', 'Small Car'), ('Sports Car / Coupe', 'Sports Car / Coupe'), ('SUV / Off-road Vehicle', 'SUV / Off-road Vehicle'), ('Van / Minibus', 'Van / Minibus'), ('Pickup Truck', 'Pickup Truck'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
