# Generated by Django 3.0.4 on 2020-04-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0002_auto_20200406_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reduced_price',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
