# Generated by Django 3.0.4 on 2020-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0003_auto_20200328_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='pictures',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
