# Generated by Django 3.0.4 on 2020-04-10 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0004_auto_20200406_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage_km',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
