# Generated by Django 3.0.4 on 2020-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0004_auto_20200324_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model_other',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
