# Generated by Django 3.0.4 on 2020-03-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0005_auto_20200324_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('creation_datetime', 'price')},
        ),
    ]
