# Generated by Django 3.0.4 on 2020-03-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0008_auto_20200325_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='pictures',
            field=models.CharField(max_length=60),
        ),
    ]
