# Generated by Django 3.0.4 on 2020-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoad', '0009_auto_20200325_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, choices=[('Abarth', 'Abarth'), ('AC', 'AC'), ('Acura', 'Acura'), ('Aixam', 'Aixam'), ('Alfa Romeo', 'Alfa Romeo'), ('ALPINA', 'ALPINA'), ('Artega', 'Artega'), ('Asia Motors', 'Asia Motors'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Austin', 'Austin'), ('Austin Healey', 'Austin Healey'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Borgward', 'Borgward'), ('Brilliance', 'Brilliance'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Casalini', 'Casalini'), ('Caterham', 'Caterham'), ('Chatenet', 'Chatenet'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroën'), ('Cobra', 'Cobra'), ('Corvette', 'Corvette'), ('Cupra', 'Cupra'), ('Dacia', 'Dacia'), ('Daewoo', 'Daewoo'), ('Daihatsu', 'Daihatsu'), ('DeTomaso', 'DeTomaso'), ('Dodge', 'Dodge'), ('Donkervoort', 'Donkervoort'), ('DS Automobiles', 'DS Automobiles'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Fisker', 'Fisker'), ('Ford', 'Ford'), ('GM', 'GM'), ('GAC Gonow', 'GAC Gonow'), ('Gemballa', 'Gemballa'), ('GMC', 'GMC'), ('Grecav', 'Grecav'), ('Hamann', 'Hamann'), ('Holden', 'Holden'), ('Honda', 'Honda'), ('Hummer', 'Hummer'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Isuzu', 'Isuzu'), ('Iveco', 'Iveco'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Koenigsegg', 'Koenigsegg'), ('KTM', 'KTM'), ('Lada', 'Lada'), ('Lamborghini', 'Lamborghini'), ('Lancia', 'Lancia'), ('Land Rover', 'Land Rover'), ('Landwind', 'Landwind'), ('Lexus', 'Lexus'), ('Ligier', 'Ligier'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Mahindra', 'Mahindra'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('MG', 'MG'), ('Microcar', 'Microcar'), ('MINI', 'MINI'), ('Mitsubishi', 'Mitsubishi'), ('Morgan', 'Morgan'), ('Nissan', 'Nissan'), ('NSU', 'NSU'), ('Oldsmobile', 'Oldsmobile'), ('Opel', 'Opel'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Piaggio', 'Piaggio'), ('Plymouth', 'Plymouth'), ('Polestar', 'Polestar'), ('Pontiac', 'Pontiac'), ('Porsche', 'Porsche'), ('Proton', 'Proton'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Rover', 'Rover'), ('Ruf', 'Ruf'), ('Saab', 'Saab'), ('Santana', 'Santana'), ('Seat', 'Seat'), ('Skoda', 'Skoda'), ('Smart', 'Smart'), ('speedART', 'speedART'), ('Spyker', 'Spyker'), ('Ssangyong', 'Ssangyong'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Talbot', 'Talbot'), ('Tata', 'Tata'), ('TECHART', 'TECHART'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Trabant', 'Trabant'), ('Triumph', 'Triumph'), ('TVR', 'TVR'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Wartburg', 'Wartburg'), ('Westfield', 'Westfield'), ('Wiesmann', 'Wiesmann'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
